### ISSUE TITLE
I get the error running as root: OSError: [Errno 19] No such device

### ISSUE THREAD

**Issue by vudumagic1968** [zeigotaro/python-sniffer#2]
python3.9
Traceback (most recent call last):
  File "/export/backups/scratch/mjobe/git/testpy/sniffer/./snifferCore.py", line 95, in <module>
    sniffer(count=10,showPort=True,showRawData=True)
  File "/export/backups/scratch/mjobe/git/testpy/sniffer/./snifferCore.py", line 71, in sniffer
    with PromiscuousSocketManager() as s:
  File "/export/backups/scratch/mjobe/git/testpy/sniffer/./snifferCore.py", line 35, in __init__
    fcntl.ioctl(s, FLAGS.SIOCGIFFLAGS, ifr) # get the flags
OSError: [Errno 19] No such device

$ uname -a
Linux engdev71.efjdfw.local 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/redhat-release
CentOS Linux release 7.7.1908 (Core)

**Comment by vudumagic1968** [comment]
contact me at mjobe@efji.com
